### ISSUE TITLE
url in setup.py

### ISSUE THREAD

**Issue by nixjdm** [mesbahamin/lektor-webdav#1]
@mesbahamin Hey Amin! Sorry I didn't realize this earlier, but I'd love it if you could add a `url` key to your `setup.py` as well. I see you went with `project_urls`, which [I can't quite yet query for](https://github.com/pypa/warehouse/issues/3831). Eventually I'll be listing those as well, but right now in order to populate the GitHub section of the new plugin page, I'm relying on the `url` key. It's also a bit more deterministic than writing a more complicated heuristic over the `project_urls` once I can query for them.

So, that's a long-winded way of saying, can you please update your `setup.py` to include the following line?
```python
url='https://github.com/mesbahamin/lektor-webdav',
```

I'm 99% sure this is the last setup.py update I'll request :)

To see what I'm talking about, see the attached screenshot of how the new plugin page will look. The PR for it isn't quite ready yet, but it's very close.

![plugin-page](https://user-images.githubusercontent.com/3431410/39676402-ceeedb2e-512f-11e8-8e11-2da3302dacf0.png)

**Comment by mesbahamin** [comment]
Done! Updated the PyPi package as well.
The new plugin page looks nice!
